CREATE SCHEMA streamkist;
REVOKE ALL ON SCHEMA streamkist FROM PUBLIC;

CREATE TABLE streamkist.guilds (
    guild_id text PRIMARY KEY,
    watch_limit integer NOT NULL DEFAULT 1 CHECK (watch_limit IN (1, 3, 5)),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE streamkist.twitch_categories (
    game_id text PRIMARY KEY,
    name text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE streamkist.channels (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id text NOT NULL REFERENCES streamkist.guilds(guild_id),
    channel_id text NOT NULL,
    game_id text NOT NULL REFERENCES streamkist.twitch_categories(game_id),
    created_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE UNIQUE INDEX streamkist_channels_active ON streamkist.channels(guild_id, channel_id, game_id)
    WHERE deleted_at IS NULL;
CREATE INDEX streamkist_channels_guild ON streamkist.channels(guild_id) WHERE deleted_at IS NULL;
CREATE TABLE streamkist.streams (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watch_id bigint NOT NULL REFERENCES streamkist.channels(id),
    stream_id text NOT NULL,
    user_id text NOT NULL,
    message_id text UNIQUE,
    snapshot jsonb NOT NULL,
    peak_viewers integer NOT NULL DEFAULT 0 CHECK (peak_viewers >= 0),
    is_live boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(watch_id, stream_id)
);
CREATE INDEX streamkist_streams_live ON streamkist.streams(watch_id) WHERE is_live;
CREATE TABLE streamkist.command_usage (
    command_name text PRIMARY KEY,
    usage_count bigint NOT NULL DEFAULT 0,
    last_used timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE streamkist.command_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_name text NOT NULL,
    guild_id text,
    channel_id text,
    execution_time bigint NOT NULL,
    options jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE streamkist.poll_lease (
    id boolean PRIMARY KEY DEFAULT true CHECK (id),
    owner text NOT NULL,
    expires_at timestamptz NOT NULL
);
