[package]
name = "zc-workshop"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
jiff.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
steam-rs.workspace = true
tokio.workspace = true
tracing.workspace = true
zc-core.workspace = true
