# lower runtime heap memory. Accept slower peak throughput for smaller containers.
smol = true

# disable anonymous crash reports/telemetry
telemetry = false

[run]
# equivalent to `bun --bun` for all `bun run` commands
# bun = true
# prevent child processes from surviving a killed bun command
noOrphans = true

[install]
logLevel = "warn"
# Only install package versions published at least 3 days ago
minimumReleaseAge = 259200

[test]
smol = true
isolate = true
preload = ["./test/preload.ts"]
#coverage = true
#coverageThreshold = 0.9
coverageSkipTestFiles = true
#randomize = true
onlyFailures = true

[test.reporter]
#dots = true
