FROM gcr.io/distroless/base-debian12

LABEL org.opencontainers.image.description="ZeepCentraal PostGraphile GraphQL server."

WORKDIR /app

COPY dist/zeepcentraal-postgraphile zeepcentraal-postgraphile

ENV NODE_ENV=production
ENV GRAPHILE_TURBO=1

EXPOSE 5000

CMD ["./zeepcentraal-postgraphile"]
