FROM gcr.io/distroless/base

WORKDIR /app

COPY dist/zeepcentraal-import-zsl zeepcentraal-import-zsl
COPY super_league_data /data/super_league_data

ENV NODE_ENV=production
ENV SUPER_LEAGUE_DATA_PATH=/data/super_league_data

CMD ["./zeepcentraal-import-zsl"]
