FROM gcr.io/distroless/base

LABEL org.opencontainers.image.description="ZeepCentraal API server."

WORKDIR /app

COPY dist/zeepcentraal-server zeepcentraal-server

ENV NODE_ENV=production

EXPOSE 3000

CMD ["./zeepcentraal-server"]
