FROM steamcmd/steamcmd:ubuntu-22@sha256:c79bd591e971c0605fcb01a4c4e54d92fe0689548385cc908acc5273020742bc

ARG SERVICE_VERSION=dev

LABEL org.opencontainers.image.description="ZeepCentraal level contest inspector with SteamCMD and deadline watcher."

WORKDIR /app

COPY --chmod=755 dist/zeepcentraal-inspector-zeep zeepcentraal-inspector-zeep

ENV NODE_ENV=production
ENV OPENTELEMETRY_SERVICE_NAME=zeepcentraal-inspector-zeep
ENV OPENTELEMETRY_SERVICE_VERSION=$SERVICE_VERSION
ENV STEAMCMD_PATH=/usr/bin/steamcmd

ENTRYPOINT ["/app/zeepcentraal-inspector-zeep"]
