export const POINTS_HISTORY_PRUNE_QUEUE_NAME = 'points-history-pruning'
export const POINTS_HISTORY_PRUNE_JOB_PRIORITY = 100
export const POINTS_HISTORY_PRUNE_DAILY_DELETE_LIMIT = 250_000
export const POINTS_HISTORY_PRUNE_BATCH_DELETE_LIMIT = 10_000
export const POINTS_HISTORY_PRUNE_ENTITY_LIMIT = 200
export const POINTS_HISTORY_PRUNE_AGE_DAYS = 28
