[package]
name = "zc-migrate"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["db-sqlx"]
db-sqlx = ["zc-database/db-sqlx"]
db-diesel = ["zc-database/db-diesel"]

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
tokio.workspace = true
zc-core.workspace = true
zc-database.workspace = true

