import { afterAll, beforeAll, beforeEach, describe, expect, mock, test } from 'bun:test'
import { SQL } from 'bun'
import { drizzle } from 'drizzle-orm/bun-sql'
import * as schema from '../schema'

// Opt-in: disposable local PostgreSQL, database/user/password all "record_test".
// RECORD_TEST_PORT=55439 bun test --isolate packages/database/src/services/recordWorldRecords.spec.ts
// Only this suite's schema is created and removed; never use application credentials.
const port = Number(process.env.RECORD_TEST_PORT ?? 0)
const client = new SQL({
	hostname: '127.0.0.1',
	port: port || 55439,
	username: 'record_test',
	password: 'record_test',
	database: 'record_test',
	max: 8,
	connection: {
		search_path: 'record_wr_test',
		statement_timeout: '5000',
		lock_timeout: '4000',
	},
})
const db = drizzle(client, { schema })
mock.module('../client', () => ({ db }))
mock.module('../config', () => ({ GHOST_FOLDER: 'ghost' }))
mock.module('../s3', () => ({ deleteFile: mock(async () => {}), uploadFile: mock(async () => {}) }))
mock.module('@zeepkist/telemetry', () => ({
	createCounter: () => ({ add: () => {} }),
	recordSpanError: () => {},
	setActiveSpanErrorStatus: () => {},
	startActiveSpan: (_name: string, callback: (span: Record<string, () => void>) => unknown) =>
		callback({ recordException: () => {}, setErrorStatus: () => {}, end: () => {} }),
}))
// Tournament behavior is outside this fixture; submission, score persistence, and locks are real.
mock.module('./trackTournament', () => ({ recordTrackTournamentResults: async () => false }))
const { submitRecord } = await import('./record')
const { persistUserPointScore } = await import('./userPointContribution')

function submit(idUser: number, idLevel: number, time: number) {
	return submitRecord({ idUser, idLevel, time, gameVersion: 'test', modVersion: 'test' })
}

async function counts() {
	return [...(await client`SELECT id_user, world_records FROM user_points ORDER BY id_user`)]
}

async function expectAccurateCounts() {
	const mismatches = await client`
		SELECT id_user FROM user_points AS points
		WHERE world_records <> (
			SELECT COUNT(*) FROM world_record_global AS wr WHERE wr.id_user = points.id_user
		)
	`
	expect(mismatches).toHaveLength(0)
}

describe.skipIf(!port)('record world record counts (PostgreSQL)', () => {
	beforeAll(async () => {
		await client`CREATE SCHEMA record_wr_test`
		// Minimal submission tables: same columns/defaults/unique keys as schema.ts.
		await client.unsafe(`
			CREATE TABLE record (
				id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				id_user integer NOT NULL, id_level integer NOT NULL, time real NOT NULL,
				game_version varchar(255) NOT NULL, mod_version varchar(255) NOT NULL,
				splits real[], speeds real[], date_created timestamptz NOT NULL DEFAULT now(),
				date_updated timestamptz
			);
			CREATE TABLE personal_best_global (
				id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				id_user integer NOT NULL, id_level integer NOT NULL,
				id_record integer NOT NULL REFERENCES record(id),
				date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz,
				UNIQUE (id_user, id_level)
			);
			CREATE TABLE world_record_global (
				id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				id_user integer NOT NULL, id_level integer NOT NULL UNIQUE,
				id_record integer NOT NULL REFERENCES record(id),
				date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz
			);
			CREATE TABLE user_points (
				id_user integer PRIMARY KEY, points integer NOT NULL DEFAULT 0,
				total_points integer NOT NULL DEFAULT 0, rank integer NOT NULL DEFAULT -1,
				world_records integer NOT NULL DEFAULT 0,
				date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz
			);
			CREATE TABLE user_point_contribution (id_user integer NOT NULL);
		`)
	})

	beforeEach(async () => {
		await client`TRUNCATE personal_best_global, world_record_global, record, user_points, user_point_contribution RESTART IDENTITY`
	})

	afterAll(async () => {
		await client`DROP SCHEMA record_wr_test CASCADE`
		await client.close()
	})

	test('first WR creates default points row and preserves return shape', async () => {
		const result = await submit(1, 1, 10)
		expect(result).toMatchObject({
			record: { idUser: 1, idLevel: 1, time: 10 },
			personalBestChanged: true,
			tournamentResultChanged: false,
		})
		expect(Object.keys(result ?? {}).sort()).toEqual([
			'personalBestChanged',
			'record',
			'tournamentResultChanged',
		])
		const [points] = await client`SELECT * FROM user_points`
		expect(points).toMatchObject({ points: 0, total_points: 0, rank: -1, world_records: 1 })
	})

	test('replacement recounts both holders, repairs stale counts, and preserves scores', async () => {
		await submit(1, 1, 10)
		await submit(1, 2, 10)
		await client`UPDATE user_points SET points = 42, total_points = 99, rank = 7, world_records = 88`
		await submit(2, 1, 9)
		expect(await counts()).toEqual([
			{ id_user: 1, world_records: 1 },
			{ id_user: 2, world_records: 1 },
		])
		const [previous] = await client`SELECT * FROM user_points WHERE id_user = 1`
		expect(previous).toMatchObject({ points: 42, total_points: 99, rank: 7 })
		await submit(2, 2, 9)
		expect(await counts()).toEqual([
			{ id_user: 1, world_records: 0 },
			{ id_user: 2, world_records: 2 },
		])
	})

	test('missing previous holder points row is recreated with zero WRs', async () => {
		await submit(1, 1, 10)
		await client`DELETE FROM user_points`
		await submit(2, 1, 9)
		expect(await counts()).toEqual([
			{ id_user: 1, world_records: 0 },
			{ id_user: 2, world_records: 1 },
		])
	})

	test('same holder improvement recounts once and skips unchanged row writes', async () => {
		await submit(1, 1, 10)
		await client`UPDATE user_points SET date_updated = '2000-01-01', world_records = 77`
		await submit(1, 1, 9)
		expect(await counts()).toEqual([{ id_user: 1, world_records: 1 }])
		await client`UPDATE user_points SET date_updated = '2000-01-01'`
		await submit(1, 1, 8)
		const [row] = await client`SELECT date_updated = '2000-01-01' AS unchanged FROM user_points`
		expect(row?.unchanged).toBe(true)
	})

	test('equal and slower records skip recount even when count is stale', async () => {
		await submit(1, 1, 10)
		await client`UPDATE user_points SET world_records = 77`
		await submit(2, 1, 10)
		await submit(3, 1, 11)
		expect(await counts()).toEqual([{ id_user: 1, world_records: 77 }])
	})

	test('recount failure rolls back record, PB, WR and both counts', async () => {
		await submit(1, 1, 10)
		await client`ALTER TABLE user_points ADD CONSTRAINT reject_new_holder CHECK (id_user <> 2)`
		try {
			await expect(submit(2, 1, 9)).rejects.toThrow()
			expect(await counts()).toEqual([{ id_user: 1, world_records: 1 }])
			expect(await client`SELECT id_user FROM record`).toHaveLength(1)
			expect(await client`SELECT id_user FROM personal_best_global`).toHaveLength(1)
			const [wr] = await client`SELECT id_user FROM world_record_global`
			expect(wr?.id_user).toBe(1)
		} finally {
			await client`ALTER TABLE user_points DROP CONSTRAINT reject_new_holder`
		}
	})

	test('concurrent first WRs and replacements on same level converge', async () => {
		await Promise.all(Array.from({ length: 8 }, (_, i) => submit(i + 1, 1, 20 - i)))
		await expectAccurateCounts()
		const [wr] = await client`SELECT id_user FROM world_record_global`
		expect(wr?.id_user).toBe(8)
		expect((await counts()).find((row) => row.id_user === 8)?.world_records).toBe(1)
	})

	test('opposite holder swaps across levels acquire score locks without deadlock', async () => {
		await submit(1, 1, 20)
		await submit(2, 2, 20)
		for (let round = 0; round < 5; round++) {
			const firstUser = round % 2 === 0 ? 2 : 1
			await Promise.all([
				submit(firstUser, 1, 19 - round),
				submit(3 - firstUser, 2, 19 - round),
			])
			await expectAccurateCounts()
		}
		expect(await counts()).toEqual([
			{ id_user: 1, world_records: 1 },
			{ id_user: 2, world_records: 1 },
		])
	})

	test('concurrent background score persistence retains current WR counts', async () => {
		await submit(1, 1, 20)
		for (let round = 0; round < 5; round++) {
			await Promise.all([
				submit((round % 2) + 1, 1, 19 - round),
				persistUserPointScore({
					idUser: 1,
					contributions: [],
					points: 42,
					totalPoints: 99,
				}),
				persistUserPointScore({
					idUser: 2,
					contributions: [],
					points: 24,
					totalPoints: 88,
				}),
			])
			await expectAccurateCounts()
		}
		const rows =
			await client`SELECT id_user, points, total_points FROM user_points ORDER BY id_user`
		expect([...rows]).toEqual([
			{ id_user: 1, points: 42, total_points: 99 },
			{ id_user: 2, points: 24, total_points: 88 },
		])
	})
})
