import {
	IconAdjustments,
	IconBook,
	IconBrandDiscord,
	IconBrandSteam,
	IconCalendarEvent,
	IconChevronLeft,
	IconChevronRight,
	IconCircleCheck,
	IconClockBolt,
	IconCode,
	IconDashboard,
	IconDatabaseOff,
	IconExclamationCircle,
	IconFlag,
	IconFlag3,
	IconLayoutSidebarLeftCollapse,
	IconLayoutSidebarLeftExpand,
	IconLink,
	IconLogin2,
	IconLogout2,
	IconMap,
	IconPalette,
	IconPlug,
	IconPlugConnected,
	IconRoute,
	IconSearch,
	IconSettings,
	IconShieldCheck,
	IconSparkles,
	IconStar,
	IconTrendingUp,
	IconTrophy,
	IconUser,
	IconUserCircle,
	IconUsers,
	IconWorld,
} from '@tabler/icons-vue'

export const tablerIcons = {
	adjustments: IconAdjustments,
	book: IconBook,
	'brand-discord': IconBrandDiscord,
	'brand-steam': IconBrandSteam,
	calendar: IconCalendarEvent,
	'chevron-left': IconChevronLeft,
	'chevron-right': IconChevronRight,
	code: IconCode,
	dashboard: IconDashboard,
	'database-off': IconDatabaseOff,
	'exclamation-circle': IconExclamationCircle,
	flag: IconFlag,
	login: IconLogin2,
	logout: IconLogout2,
	map: IconMap,
	palette: IconPalette,
	plug: IconPlug,
	route: IconRoute,
	search: IconSearch,
	settings: IconSettings,
	'sidebar-collapse': IconLayoutSidebarLeftCollapse,
	'sidebar-expand': IconLayoutSidebarLeftExpand,
	trophy: IconTrophy,
	user: IconUser,
	'user-circle': IconUserCircle,
	users: IconUsers,
	world: IconWorld,
	'external-link': IconLink,
	'circle-check': IconCircleCheck,
	'plug-connected': IconPlugConnected,
	'shield-check': IconShieldCheck,
	'flag-3': IconFlag3,
	'trending-up': IconTrendingUp,
	sparkles: IconSparkles,
	'clock-bolt': IconClockBolt,
	star: IconStar,
}

export type TablerIconName = keyof typeof tablerIcons
