import {
	IconAdjustments,
	IconArrowDownFromArc,
	IconArrowNarrowDownDashed,
	IconBook,
	IconBrandDiscord,
	IconBrandSteam,
	IconCalendarEvent,
	IconCalendarStats,
	IconChevronLeft,
	IconChevronRight,
	IconChevronsLeft,
	IconChevronsRight,
	IconCircleCheck,
	IconClock,
	IconClock24,
	IconClockBolt,
	IconCode,
	IconDashboard,
	IconDatabaseOff,
	IconExclamationCircle,
	IconFlag,
	IconFlag3,
	IconGauge,
	IconHandStop,
	IconHourglass,
	IconLayoutSidebarLeftCollapse,
	IconLayoutSidebarLeftExpand,
	IconLink,
	IconLoader2,
	IconLogin2,
	IconLogout2,
	IconMap,
	IconPalette,
	IconPlug,
	IconPlugConnected,
	IconRoad,
	IconRoute,
	IconSearch,
	IconSettings,
	IconShieldCheck,
	IconSparkles,
	IconStar,
	IconSteeringWheel,
	IconTrendingUp,
	IconTrophy,
	IconUser,
	IconUserCircle,
	IconUsers,
	IconVolume,
	IconWind,
	IconWorld,
} from '@tabler/icons-vue'

export const tablerIcons = {
	'arrow-down-from-arc': IconArrowDownFromArc,
	'arrow-narrow-down-dashed': IconArrowNarrowDownDashed,
	'brand-discord': IconBrandDiscord,
	'brand-steam': IconBrandSteam,
	'calendar-stats': IconCalendarStats,
	'chevron-left': IconChevronLeft,
	'chevron-right': IconChevronRight,
	'chevrons-left': IconChevronsLeft,
	'chevrons-right': IconChevronsRight,
	'circle-check': IconCircleCheck,
	'clock-24': IconClock24,
	'clock-bolt': IconClockBolt,
	'database-off': IconDatabaseOff,
	'exclamation-circle': IconExclamationCircle,
	'external-link': IconLink,
	'flag-3': IconFlag3,
	'hand-stop': IconHandStop,
	'loader-2': IconLoader2,
	'plug-connected': IconPlugConnected,
	'shield-check': IconShieldCheck,
	'sidebar-collapse': IconLayoutSidebarLeftCollapse,
	'sidebar-expand': IconLayoutSidebarLeftExpand,
	'steering-wheel': IconSteeringWheel,
	'trending-up': IconTrendingUp,
	'user-circle': IconUserCircle,
	adjustments: IconAdjustments,
	book: IconBook,
	calendar: IconCalendarEvent,
	clock: IconClock,
	code: IconCode,
	dashboard: IconDashboard,
	flag: IconFlag,
	gauge: IconGauge,
	hourglass: IconHourglass,
	login: IconLogin2,
	logout: IconLogout2,
	map: IconMap,
	palette: IconPalette,
	plug: IconPlug,
	road: IconRoad,
	route: IconRoute,
	search: IconSearch,
	settings: IconSettings,
	sparkles: IconSparkles,
	star: IconStar,
	trophy: IconTrophy,
	user: IconUser,
	users: IconUsers,
	volume: IconVolume,
	wind: IconWind,
	world: IconWorld,
}

export type TablerIconName = keyof typeof tablerIcons
