CREATE TABLE "auth" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer,
	"access_token" text,
	"access_token_expiry" bigint,
	"refresh_token" text,
	"refresh_token_expiry" bigint,
	"type" integer,
	"provider" varchar DEFAULT 'invalid' NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "favourite" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "favorites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone,
	"id_level" integer NOT NULL,
	CONSTRAINT "UQ_favourites_user_level" UNIQUE("id_user","id_level")
);
--> statement-breakpoint
CREATE TABLE "level" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "level_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"hash" text NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone,
	CONSTRAINT "level_pk" UNIQUE("hash")
);
--> statement-breakpoint
CREATE TABLE "level_item" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "level_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_level" integer NOT NULL,
	"workshop_id" bigint NOT NULL,
	"author_id" bigint NOT NULL,
	"name" text NOT NULL,
	"image_url" text NOT NULL,
	"file_author" text NOT NULL,
	"file_uid" text NOT NULL,
	"validation_time_author" real NOT NULL,
	"validation_time_gold" real NOT NULL,
	"validation_time_silver" real NOT NULL,
	"validation_time_bronze" real NOT NULL,
	"deleted" boolean NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "level_metadata" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "level_metadata_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_level" integer NOT NULL,
	"amount_checkpoints" integer NOT NULL,
	"amount_finishes" integer NOT NULL,
	"amount_blocks" integer NOT NULL,
	"type_ground" integer NOT NULL,
	"type_skybox" integer NOT NULL,
	"blocks" jsonb NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "level_points" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "level_points_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_level" integer NOT NULL,
	"points" integer NOT NULL,
	"rating" real DEFAULT 0.5 NOT NULL,
	"modifier_length" real DEFAULT 1 NOT NULL,
	"modifier_competitiveness" real DEFAULT 1 NOT NULL,
	"modifier_rating" real DEFAULT 1 NOT NULL,
	"modifier_popularity" real DEFAULT 1 NOT NULL,
	"cut_penalty" real DEFAULT 1 NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "level_points_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "level_points_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_level" integer NOT NULL,
	"points" integer NOT NULL,
	"rating" real DEFAULT 0.5 NOT NULL,
	"modifier_length" real DEFAULT 1 NOT NULL,
	"modifier_competitiveness" real DEFAULT 1 NOT NULL,
	"modifier_rating" real DEFAULT 1 NOT NULL,
	"modifier_popularity" real DEFAULT 1 NOT NULL,
	"cut_penalty" real DEFAULT 1 NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "level_request" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"workshop_id" bigint NOT NULL,
	"uid" text,
	"hash" text,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "personal_best_global" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "personal_bests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_record" integer NOT NULL,
	"id_user" integer NOT NULL,
	"id_level" integer NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone,
	CONSTRAINT "UQ_personal_bests_user_level" UNIQUE("id_user","id_level")
);
--> statement-breakpoint
CREATE TABLE "record" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"time" real NOT NULL,
	"game_version" varchar(255) NOT NULL,
	"id_level" integer NOT NULL,
	"mod_version" varchar(255) NOT NULL,
	"splits" real[],
	"speeds" real[],
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "record_media" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_record" integer NOT NULL,
	"ghost_url" text,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone,
	CONSTRAINT "UQ_record_media_record" UNIQUE("id_record")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"steam_name" varchar(255),
	"banned" boolean DEFAULT false NOT NULL,
	"steam_id" bigint,
	"discord_id" bigint,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "user_points" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "player_points_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"points" integer DEFAULT 0 NOT NULL,
	"total_points" integer DEFAULT 0 NOT NULL,
	"rank" integer DEFAULT -1 NOT NULL,
	"world_records" integer DEFAULT 0 NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "user_points_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_points_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"points" integer NOT NULL,
	"total_points" integer DEFAULT 0 NOT NULL,
	"rank" integer DEFAULT -1 NOT NULL,
	"world_records" integer DEFAULT 0 NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "version" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"minimum" text,
	"latest" text,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "vote" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "vote_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"id_level" integer NOT NULL,
	"value" integer NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "world_record_global" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "world_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_record" integer NOT NULL,
	"id_level" integer NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone,
	"id_user" integer NOT NULL,
	CONSTRAINT "UQ_world_records_level" UNIQUE("id_level")
);
--> statement-breakpoint
CREATE TABLE "zsl_level" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "zsl_level_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_round" integer NOT NULL,
	"id_level" integer NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zsl_level_result" (
	"id_level" integer NOT NULL,
	"id_user" integer NOT NULL,
	"id_record" integer,
	"position" integer NOT NULL,
	"points" integer NOT NULL,
	"time" real NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone,
	CONSTRAINT "zsl_level_result_id_level_id_user_pk" PRIMARY KEY("id_level","id_user")
);
--> statement-breakpoint
CREATE TABLE "zsl_points_structure" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "zsl_points_structure_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"points" integer[] NOT NULL,
	"minimum_points" integer NOT NULL,
	"best_of" integer NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zsl_round" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "zsl_round_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_season" integer NOT NULL,
	"name" text NOT NULL,
	"round" integer NOT NULL,
	"workshop_id" bigint NOT NULL,
	"event_date" timestamp with time zone NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone,
	CONSTRAINT "UQ_zsl_round_season_round" UNIQUE("id_season","round")
);
--> statement-breakpoint
CREATE TABLE "zsl_round_result" (
	"id_round" integer NOT NULL,
	"id_user" integer NOT NULL,
	"position" integer NOT NULL,
	"points" integer NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone,
	CONSTRAINT "zsl_round_result_id_round_id_user_pk" PRIMARY KEY("id_round","id_user")
);
--> statement-breakpoint
CREATE TABLE "zsl_season" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "zsl_season_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_points_structure" integer NOT NULL,
	"name" text NOT NULL,
	"start_date" timestamp with time zone NOT NULL,
	"end_date" timestamp with time zone NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zsl_season_result" (
	"id_season" integer NOT NULL,
	"id_user" integer NOT NULL,
	"position" integer NOT NULL,
	"points" integer NOT NULL,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone,
	CONSTRAINT "zsl_season_result_id_season_id_user_pk" PRIMARY KEY("id_season","id_user")
);
--> statement-breakpoint
ALTER TABLE "auth" ADD CONSTRAINT "auth_user_foreign" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "favourite" ADD CONSTRAINT "favorite_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "favourite" ADD CONSTRAINT "favorites_user_foreign" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "level_item" ADD CONSTRAINT "level_item_id_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "level_metadata" ADD CONSTRAINT "level_metadata_id_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "level_points" ADD CONSTRAINT "level_points_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD CONSTRAINT "level_points_history_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal_best_global" ADD CONSTRAINT "personal_best_global_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal_best_global" ADD CONSTRAINT "personal_bests_global_record_fkey" FOREIGN KEY ("id_record") REFERENCES "public"."record"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal_best_global" ADD CONSTRAINT "personal_bests_global_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "record" ADD CONSTRAINT "record_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "record" ADD CONSTRAINT "records_user_foreign" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "record_media" ADD CONSTRAINT "media_record_fkey" FOREIGN KEY ("id_record") REFERENCES "public"."record"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_points" ADD CONSTRAINT "player_points_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_points_history" ADD CONSTRAINT "user_points_history_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vote" ADD CONSTRAINT "vote_id_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vote" ADD CONSTRAINT "vote_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "world_record_global" ADD CONSTRAINT "world_record_global_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "world_record_global" ADD CONSTRAINT "world_records_global_record_fkey" FOREIGN KEY ("id_record") REFERENCES "public"."record"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "world_record_global" ADD CONSTRAINT "world_records_global_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zsl_level" ADD CONSTRAINT "zsl_level_round_fkey" FOREIGN KEY ("id_round") REFERENCES "public"."zsl_round"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zsl_level" ADD CONSTRAINT "zsl_level_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zsl_level_result" ADD CONSTRAINT "zsl_level_result_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."zsl_level"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zsl_level_result" ADD CONSTRAINT "zsl_level_result_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zsl_level_result" ADD CONSTRAINT "zsl_level_result_record_fkey" FOREIGN KEY ("id_record") REFERENCES "public"."record"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zsl_round" ADD CONSTRAINT "zsl_round_season_fkey" FOREIGN KEY ("id_season") REFERENCES "public"."zsl_season"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zsl_round_result" ADD CONSTRAINT "zsl_round_result_round_fkey" FOREIGN KEY ("id_round") REFERENCES "public"."zsl_round"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zsl_round_result" ADD CONSTRAINT "zsl_round_result_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zsl_season" ADD CONSTRAINT "zsl_season_points_structure_fkey" FOREIGN KEY ("id_points_structure") REFERENCES "public"."zsl_points_structure"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zsl_season_result" ADD CONSTRAINT "zsl_season_result_season_fkey" FOREIGN KEY ("id_season") REFERENCES "public"."zsl_season"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zsl_season_result" ADD CONSTRAINT "zsl_season_result_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "IX_auth_user" ON "auth" USING btree ("id_user");--> statement-breakpoint
CREATE INDEX "IX_favorites_level" ON "favourite" USING btree ("id_level");--> statement-breakpoint
CREATE INDEX "IX_favorites_user" ON "favourite" USING btree ("id_user");--> statement-breakpoint
CREATE INDEX "IX_level_item_level" ON "level_item" USING btree ("id_level");--> statement-breakpoint
CREATE INDEX "IX_level_metadata_level" ON "level_metadata" USING btree ("id_level");--> statement-breakpoint
CREATE UNIQUE INDEX "UQ_level_points_level" ON "level_points" USING btree ("id_level");--> statement-breakpoint
CREATE UNIQUE INDEX "UQ_level_points_history_level" ON "level_points_history" USING btree ("id_level","date_created" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "IX_level_request_hash" ON "level_request" USING btree ("hash");--> statement-breakpoint
CREATE INDEX "IX_level_request_workshop_id" ON "level_request" USING btree ("workshop_id");--> statement-breakpoint
CREATE INDEX "IX_personal_bests_level_user" ON "personal_best_global" USING btree ("id_level","id_user");--> statement-breakpoint
CREATE INDEX "IX_personal_bests_record" ON "personal_best_global" USING btree ("id_record");--> statement-breakpoint
CREATE INDEX "IX_personal_bests_user" ON "personal_best_global" USING btree ("id_user");--> statement-breakpoint
CREATE INDEX "IX_personal_bests_user_level_record" ON "personal_best_global" USING btree ("id_user","id_level","id_record");--> statement-breakpoint
CREATE INDEX "IX_personal_bests_date_created" ON "personal_best_global" USING btree ("date_created");--> statement-breakpoint
CREATE INDEX "IX_records_id_time" ON "record" USING btree ("id_level","time");--> statement-breakpoint
CREATE INDEX "IX_records_level" ON "record" USING btree ("id_level");--> statement-breakpoint
CREATE INDEX "IX_records_level_time" ON "record" USING btree ("id_level","time");--> statement-breakpoint
CREATE INDEX "IX_records_time_id" ON "record" USING btree ("time","id_level");--> statement-breakpoint
CREATE INDEX "IX_records_user" ON "record" USING btree ("id_user");--> statement-breakpoint
CREATE INDEX "IX_records_date_created" ON "record" USING btree ("date_created");--> statement-breakpoint
CREATE INDEX "IX_records_user_level_time" ON "record" USING btree ("id_user","id_level","time");--> statement-breakpoint
CREATE INDEX "IX_records_user_level_date_created" ON "record" USING btree ("id_user","id_level","date_created");--> statement-breakpoint
CREATE INDEX "IX_media_record" ON "record_media" USING btree ("id_record");--> statement-breakpoint
CREATE UNIQUE INDEX "UQ_player_points_user" ON "user_points" USING btree ("id_user");--> statement-breakpoint
CREATE UNIQUE INDEX "UQ_user_points_history_user" ON "user_points_history" USING btree ("id_user","date_created" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "IX_vote_user_level" ON "vote" USING btree ("id_user","id_level");--> statement-breakpoint
CREATE INDEX "IX_world_records_level" ON "world_record_global" USING btree ("id_level");--> statement-breakpoint
CREATE INDEX "IX_world_records_record" ON "world_record_global" USING btree ("id_record");--> statement-breakpoint
CREATE INDEX "IX_world_records_user" ON "world_record_global" USING btree ("id_user");--> statement-breakpoint
CREATE INDEX "IX_world_records_date_created" ON "world_record_global" USING btree ("date_created");--> statement-breakpoint
CREATE INDEX "IX_world_records_user_level_record" ON "world_record_global" USING btree ("id_user","id_level","id_record");--> statement-breakpoint
CREATE INDEX "IX_zsl_level_round" ON "zsl_level" USING btree ("id_round");--> statement-breakpoint
CREATE INDEX "IX_zsl_level_id" ON "zsl_level" USING btree ("id_level");--> statement-breakpoint
CREATE INDEX "IX_zsl_level_result_level" ON "zsl_level_result" USING btree ("id_level");--> statement-breakpoint
CREATE INDEX "IX_zsl_level_result_user" ON "zsl_level_result" USING btree ("id_user");--> statement-breakpoint
CREATE INDEX "IX_zsl_level_result_record" ON "zsl_level_result" USING btree ("id_record");--> statement-breakpoint
CREATE INDEX "IX_zsl_level_result_position" ON "zsl_level_result" USING btree ("position");--> statement-breakpoint
CREATE INDEX "IX_zsl_level_result_date_created" ON "zsl_level_result" USING btree ("date_created");--> statement-breakpoint
CREATE INDEX "IX_zsl_round_season" ON "zsl_round" USING btree ("id_season");--> statement-breakpoint
CREATE INDEX "IX_zsl_round_workshop_id" ON "zsl_round" USING btree ("workshop_id");--> statement-breakpoint
CREATE INDEX "IX_zsl_round_event_date" ON "zsl_round" USING btree ("event_date");--> statement-breakpoint
CREATE INDEX "IX_zsl_round_result_round" ON "zsl_round_result" USING btree ("id_round");--> statement-breakpoint
CREATE INDEX "IX_zsl_round_result_user" ON "zsl_round_result" USING btree ("id_user");--> statement-breakpoint
CREATE INDEX "IX_zsl_round_result_position" ON "zsl_round_result" USING btree ("position");--> statement-breakpoint
CREATE INDEX "IX_zsl_round_result_date_created" ON "zsl_round_result" USING btree ("date_created");--> statement-breakpoint
CREATE INDEX "IX_zsl_season_result_season" ON "zsl_season_result" USING btree ("id_season");--> statement-breakpoint
CREATE INDEX "IX_zsl_season_result_user" ON "zsl_season_result" USING btree ("id_user");--> statement-breakpoint
CREATE INDEX "IX_zsl_season_result_position" ON "zsl_season_result" USING btree ("position");--> statement-breakpoint
CREATE INDEX "IX_zsl_season_result_date_created" ON "zsl_season_result" USING btree ("date_created");