CREATE TABLE "level_points_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "level_points_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_level" integer NOT NULL,
	"points" integer NOT NULL,
	"date_created" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_points_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_points_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"points" integer NOT NULL,
	"total_points" integer DEFAULT 0 NOT NULL,
	"rank" integer DEFAULT -1 NOT NULL,
	"world_records" integer DEFAULT 0 NOT NULL,
	"date_created" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "user_points" ALTER COLUMN "rank" SET DEFAULT -1;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD CONSTRAINT "level_points_history_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_points_history" ADD CONSTRAINT "user_points_history_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "UQ_level_points_history_level" ON "level_points_history" USING btree ("id_level","date_created" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "UQ_user_points_history_user" ON "user_points_history" USING btree ("id_user","date_created" DESC NULLS LAST);