CREATE TABLE "user_point_contribution" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_point_contribution_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"id_level" integer NOT NULL,
	"id_record" integer NOT NULL,
	"contribution_rank" integer NOT NULL,
	"level_position" integer NOT NULL,
	"level_points" integer NOT NULL,
	"level_decayed_points" real NOT NULL,
	"player_decayed_points" real NOT NULL,
	"date_calculated" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "UQ_user_point_contribution_user_level" UNIQUE("id_user","id_level")
);
--> statement-breakpoint
ALTER TABLE "user_point_contribution" ADD CONSTRAINT "user_point_contribution_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_point_contribution" ADD CONSTRAINT "user_point_contribution_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_point_contribution" ADD CONSTRAINT "user_point_contribution_record_fkey" FOREIGN KEY ("id_record") REFERENCES "public"."record"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "IX_user_point_contribution_user_contribution_rank" ON "user_point_contribution" USING btree ("id_user","contribution_rank");--> statement-breakpoint
CREATE INDEX "IX_user_point_contribution_level" ON "user_point_contribution" USING btree ("id_level");
