CREATE TABLE "record_statistic" (
	"id_record" integer PRIMARY KEY NOT NULL,
	"frame_count" integer,
	"duration" real,
	"distance_travelled" real,
	"distance_in_air" real,
	"distance_on_ground" real,
	"time_in_air" real,
	"time_on_ground" real,
	"average_speed" real,
	"top_speed" real,
	"arms_up_count" integer,
	"arms_up_time" real,
	"brake_count" integer,
	"brake_time" real,
	"turn_left_count" integer,
	"turn_left_time" real,
	"turn_right_count" integer,
	"turn_right_time" real,
	"horn_count" integer,
	"horn_time" real,
	"soap_time" real,
	"offroad_time" real,
	"paraglider_time" real,
	"distance_on_tarmac" real,
	"distance_on_grass" real,
	"distance_on_sand" real,
	"distance_on_snow" real,
	"distance_on_ice" real,
	"distance_on_soap" real,
	"distance_on_metal" real,
	"time_on_tarmac" real,
	"time_on_grass" real,
	"time_on_sand" real,
	"time_on_snow" real,
	"time_on_ice" real,
	"time_on_soap" real,
	"time_on_metal" real,
	"date_created" timestamp with time zone DEFAULT now() NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "record_statistic" ADD CONSTRAINT "record_statistic_record_fkey" FOREIGN KEY ("id_record") REFERENCES "public"."record"("id") ON DELETE cascade ON UPDATE no action;
