ALTER TABLE "level_points" ADD COLUMN "sample_size" integer;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "leaderboard_confidence" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "input_sample_size" integer;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "input_coverage" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "state_sample_size" integer;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "surface_sample_size" integer;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "velocity_sample_size" integer;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "competitiveness_score" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "world_record_difficulty_score" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "participation_score" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "passive_play_severity" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "modifier_afk" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "passive_run_ratio" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "passive_top_10_share" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "best_passive_rank" integer;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "best_passive_gap" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "driver_engagement_score" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "world_record_margin" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "top_5_spread" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "top_10_spread" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "top_50_spread" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "wr_challenger_count" integer;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "world_record_optimization_score" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "leaderboard_anomaly_score" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "telemetry_anomaly_score" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "world_record_excluded" boolean;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "path_consistency_score" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "speed_consistency_score" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "route_consistency_score" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "surface_diversity_score" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "mature_vote_count" integer;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "typical_distance" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "typical_average_speed" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "typical_max_speed" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "typical_air_time_share" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "typical_ground_time_share" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "typical_slip_share" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "typical_ragdoll_share" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "typical_average_angular_velocity" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "typical_average_gforce" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "median_steering_share" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "q25_steering_share" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "low_steering_ratio" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "zero_control_ratio" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "median_brake_share" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "median_arms_up_share" real;--> statement-breakpoint
ALTER TABLE "level_points" ADD COLUMN "median_control_transition_rate" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "sample_size" integer;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "leaderboard_confidence" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "input_sample_size" integer;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "input_coverage" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "state_sample_size" integer;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "surface_sample_size" integer;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "velocity_sample_size" integer;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "competitiveness_score" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "world_record_difficulty_score" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "participation_score" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "passive_play_severity" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "modifier_afk" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "passive_run_ratio" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "passive_top_10_share" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "best_passive_rank" integer;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "best_passive_gap" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "driver_engagement_score" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "world_record_margin" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "top_5_spread" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "top_10_spread" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "top_50_spread" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "wr_challenger_count" integer;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "world_record_optimization_score" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "leaderboard_anomaly_score" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "telemetry_anomaly_score" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "world_record_excluded" boolean;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "path_consistency_score" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "speed_consistency_score" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "route_consistency_score" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "surface_diversity_score" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "mature_vote_count" integer;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "typical_distance" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "typical_average_speed" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "typical_max_speed" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "typical_air_time_share" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "typical_ground_time_share" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "typical_slip_share" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "typical_ragdoll_share" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "typical_average_angular_velocity" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "typical_average_gforce" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "median_steering_share" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "q25_steering_share" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "low_steering_ratio" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "zero_control_ratio" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "median_brake_share" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "median_arms_up_share" real;--> statement-breakpoint
ALTER TABLE "level_points_history" ADD COLUMN "median_control_transition_rate" real;--> statement-breakpoint
ALTER TABLE "record_statistic" ADD COLUMN "ghost_version" integer;--> statement-breakpoint
ALTER TABLE "record_statistic" ADD COLUMN "has_input_data" boolean;--> statement-breakpoint
ALTER TABLE "record_statistic" ADD COLUMN "has_air_data" boolean;--> statement-breakpoint
ALTER TABLE "record_statistic" ADD COLUMN "has_wheel_data" boolean;--> statement-breakpoint
ALTER TABLE "record_statistic" ADD COLUMN "has_slip_data" boolean;--> statement-breakpoint
ALTER TABLE "record_statistic" ADD COLUMN "has_state_data" boolean;--> statement-breakpoint
ALTER TABLE "record_statistic" ADD COLUMN "has_surface_data" boolean;--> statement-breakpoint
ALTER TABLE "record_statistic" ADD COLUMN "has_velocity_data" boolean;--> statement-breakpoint
ALTER TABLE "record_statistic" ADD COLUMN "has_ragdoll_data" boolean;--> statement-breakpoint
ALTER TABLE "record_statistic" ADD COLUMN "time_any_driver_input" real;--> statement-breakpoint
ALTER TABLE "record_statistic" ADD COLUMN "driver_input_transition_count" integer;