DROP INDEX "IX_level_points_popularity_level";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "modifier_popularity";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "cut_penalty";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "sample_size";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "leaderboard_confidence";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "input_sample_size";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "input_coverage";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "air_sample_size";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "wheel_sample_size";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "slip_sample_size";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "ragdoll_sample_size";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "state_sample_size";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "surface_sample_size";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "velocity_sample_size";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "competitiveness_score";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "world_record_difficulty_score";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "participation_score";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "passive_play_severity";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "modifier_afk";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "passive_run_ratio";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "passive_top_10_share";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "best_passive_rank";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "best_passive_gap";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "driver_engagement_score";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "world_record_margin";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "top_5_spread";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "top_10_spread";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "top_50_spread";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "wr_challenger_count";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "world_record_optimization_score";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "leaderboard_anomaly_score";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "telemetry_anomaly_score";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "path_consistency_score";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "speed_consistency_score";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "route_consistency_score";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "surface_diversity_score";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "mature_vote_count";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "typical_distance";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "typical_average_speed";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "typical_max_speed";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "typical_air_time_share";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "typical_ground_time_share";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "typical_slip_share";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "typical_ragdoll_share";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "typical_average_angular_velocity";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "typical_average_gforce";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "median_steering_share";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "q25_steering_share";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "low_steering_ratio";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "zero_control_ratio";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "median_brake_share";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "median_arms_up_share";--> statement-breakpoint
ALTER TABLE "level_points" DROP COLUMN "median_control_transition_rate";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "modifier_popularity";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "cut_penalty";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "sample_size";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "leaderboard_confidence";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "input_sample_size";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "input_coverage";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "air_sample_size";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "wheel_sample_size";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "slip_sample_size";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "ragdoll_sample_size";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "state_sample_size";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "surface_sample_size";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "velocity_sample_size";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "competitiveness_score";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "world_record_difficulty_score";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "participation_score";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "passive_play_severity";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "modifier_afk";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "passive_run_ratio";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "passive_top_10_share";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "best_passive_rank";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "best_passive_gap";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "driver_engagement_score";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "world_record_margin";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "top_5_spread";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "top_10_spread";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "top_50_spread";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "wr_challenger_count";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "world_record_optimization_score";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "leaderboard_anomaly_score";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "telemetry_anomaly_score";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "path_consistency_score";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "speed_consistency_score";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "route_consistency_score";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "surface_diversity_score";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "mature_vote_count";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "typical_distance";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "typical_average_speed";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "typical_max_speed";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "typical_air_time_share";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "typical_ground_time_share";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "typical_slip_share";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "typical_ragdoll_share";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "typical_average_angular_velocity";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "typical_average_gforce";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "median_steering_share";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "q25_steering_share";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "low_steering_ratio";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "zero_control_ratio";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "median_brake_share";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "median_arms_up_share";--> statement-breakpoint
ALTER TABLE "level_points_history" DROP COLUMN "median_control_transition_rate";