-- Isolated test fixture. Current Rust column types. Never use as production baseline or migration.
CREATE TABLE public."auth" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "id_user" integer,
 "access_token" text,
 "access_token_expiry" bigint,
 "refresh_token" text,
 "refresh_token_hash" text,
 "refresh_token_expiry" bigint,
 "type" integer,
 "provider" varchar NOT NULL DEFAULT '',
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."level" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "hash" text NOT NULL DEFAULT '',
 "xx_hash" text NOT NULL DEFAULT '',
 "simhash" bigint,
 "adventure" boolean NOT NULL DEFAULT false,
 "has_records" boolean NOT NULL DEFAULT false,
 "record_count" bigint NOT NULL DEFAULT 0,
 "publicly_visible" boolean NOT NULL DEFAULT true,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."level_item" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "id_level" integer NOT NULL DEFAULT 0,
 "workshop_id" bigint NOT NULL DEFAULT 0,
 "author_id" bigint NOT NULL DEFAULT 0,
 "name" text NOT NULL DEFAULT '',
 "image_url" text NOT NULL DEFAULT '',
 "file_author" text NOT NULL DEFAULT '',
 "file_uid" text NOT NULL DEFAULT '',
 "validation_time_author" real NOT NULL DEFAULT 0,
 "validation_time_gold" real NOT NULL DEFAULT 0,
 "validation_time_silver" real NOT NULL DEFAULT 0,
 "validation_time_bronze" real NOT NULL DEFAULT 0,
 "deleted" boolean NOT NULL DEFAULT false,
 "publicly_visible" boolean NOT NULL DEFAULT true,
 "rtm_sample_key" double precision NOT NULL DEFAULT 0,
 "created_at" timestamptz NOT NULL DEFAULT now(),
 "updated_at" timestamptz NOT NULL DEFAULT now(),
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."level_metadata" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "id_level" integer NOT NULL DEFAULT 0,
 "amount_checkpoints" integer NOT NULL DEFAULT 0,
 "amount_finishes" integer NOT NULL DEFAULT 0,
 "amount_blocks" integer NOT NULL DEFAULT 0,
 "type_ground" integer NOT NULL DEFAULT 0,
 "type_skybox" integer NOT NULL DEFAULT 0,
 "environment" jsonb,
 "format" integer NOT NULL DEFAULT 0,
 "blocks" jsonb NOT NULL DEFAULT '{}',
 "publicly_visible" boolean NOT NULL DEFAULT true,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."level_points" (
 "id_level" integer NOT NULL DEFAULT 0,
 "points" integer NOT NULL DEFAULT 0,
 "rating" real NOT NULL DEFAULT 0,
 "modifier_length" real NOT NULL DEFAULT 0,
 "modifier_evidence" real NOT NULL DEFAULT 0,
 "modifier_quality" real NOT NULL DEFAULT 0,
 "modifier_rating" real NOT NULL DEFAULT 0,
 "complexity_confidence" real,
 "complexity_score" real,
 "field_strength" real,
 "quality_score" real,
 "skill_alignment" real,
 "skill_confidence" real,
 "skill_sample_size" integer,
 "skill_score" real,
 "skill_separation" real,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."level_request" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "workshop_id" bigint NOT NULL DEFAULT 0,
 "uid" text,
 "hash" text,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."personal_best_global" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "id_record" integer NOT NULL DEFAULT 0,
 "id_user" integer NOT NULL DEFAULT 0,
 "id_level" integer NOT NULL DEFAULT 0,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."record" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "id_user" integer NOT NULL DEFAULT 0,
 "time" real NOT NULL DEFAULT 0,
 "game_version" varchar NOT NULL DEFAULT '',
 "id_level" integer NOT NULL DEFAULT 0,
 "mod_version" varchar NOT NULL DEFAULT '',
 "splits" real[],
 "speeds" real[],
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."record_media" (
 "id_record" integer NOT NULL DEFAULT 0,
 "ghost_url" text,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."record_statistic" (
 "id_record" integer NOT NULL DEFAULT 0,
 "ghost_version" integer,
 "has_input_data" boolean,
 "has_air_data" boolean,
 "has_wheel_data" boolean,
 "has_slip_data" boolean,
 "has_state_data" boolean,
 "has_surface_data" boolean,
 "has_velocity_data" boolean,
 "has_ragdoll_data" boolean,
 "time_any_driver_input" real,
 "driver_input_transition_count" integer,
 "frame_count" integer,
 "time" real,
 "distance" real,
 "distance_in_air" real,
 "distance_on_ground" real,
 "distance_on_1_wheel" real,
 "distance_on_2_wheels" real,
 "distance_on_3_wheels" real,
 "distance_on_4_wheels" real,
 "time_in_air" real,
 "time_on_ground" real,
 "time_on_1_wheel" real,
 "time_on_2_wheels" real,
 "time_on_3_wheels" real,
 "time_on_4_wheels" real,
 "average_speed" real,
 "max_speed" real,
 "arms_up_count" integer,
 "arms_up_time" real,
 "brake_count" integer,
 "brake_time" real,
 "turn_left_count" integer,
 "turn_left_time" real,
 "turn_right_count" integer,
 "turn_right_time" real,
 "horn_count" integer,
 "horn_time" real,
 "distance_slipping" real,
 "distance_paraglider" real,
 "distance_offroad_wheels" real,
 "distance_soap_wheels" real,
 "distance_on_monorail" real,
 "distance_parked" real,
 "distance_ragdoll" real,
 "time_slipping" real,
 "time_paraglider" real,
 "time_offroad_wheels" real,
 "time_soap_wheels" real,
 "time_on_monorail" real,
 "time_parked" real,
 "time_ragdoll" real,
 "distance_on_tarmac" real,
 "distance_on_grass" real,
 "distance_on_sand" real,
 "distance_on_ice1" real,
 "distance_on_ice2" real,
 "distance_on_ice3" real,
 "distance_on_soap" real,
 "distance_on_wood" real,
 "distance_on_mud" real,
 "time_on_tarmac" real,
 "time_on_grass" real,
 "time_on_sand" real,
 "time_on_ice1" real,
 "time_on_ice2" real,
 "time_on_ice3" real,
 "time_on_soap" real,
 "time_on_wood" real,
 "time_on_mud" real,
 "average_velocity" real,
 "max_velocity" real,
 "average_angular_velocity" real,
 "max_angular_velocity" real,
 "average_gforce" real,
 "max_gforce" real,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."track_tournament" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "type" integer NOT NULL DEFAULT 0,
 "slug" text NOT NULL DEFAULT '',
 "id_level" integer NOT NULL DEFAULT 0,
 "start_at" timestamptz NOT NULL DEFAULT now(),
 "end_at" timestamptz NOT NULL DEFAULT now(),
 "finalized_at" timestamptz,
 "points_version" integer NOT NULL DEFAULT 0,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."track_tournament_result" (
 "id_tournament" integer NOT NULL DEFAULT 0,
 "id_user" integer NOT NULL DEFAULT 0,
 "id_record" integer NOT NULL DEFAULT 0,
 "time" real NOT NULL DEFAULT 0,
 "rank" integer NOT NULL DEFAULT 0,
 "points" integer NOT NULL DEFAULT 0,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."user" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "steam_name" varchar,
 "banned" boolean NOT NULL DEFAULT false,
 "steam_id" bigint,
 "discord_id" bigint,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."version" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "minimum" text,
 "latest" text,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz
);
CREATE TABLE public."workshop_item" (
 "workshop_id" bigint NOT NULL DEFAULT 0,
 "author_id" bigint NOT NULL DEFAULT 0,
 "name" text NOT NULL DEFAULT '',
 "image_url" text NOT NULL DEFAULT '',
 "visibility" smallint NOT NULL DEFAULT 0,
 "publicly_visible" boolean NOT NULL DEFAULT true,
 "file_size" integer NOT NULL DEFAULT 0,
 "created_at" timestamptz NOT NULL DEFAULT now(),
 "updated_at" timestamptz NOT NULL DEFAULT now(),
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public."world_record_global" (
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "id_record" integer NOT NULL DEFAULT 0,
 "id_level" integer NOT NULL DEFAULT 0,
 "date_created" timestamptz NOT NULL DEFAULT now(),
 "date_updated" timestamptz,
 "id_user" integer NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX ON public."user" (steam_id);
CREATE UNIQUE INDEX ON public."level" (xx_hash);
CREATE UNIQUE INDEX ON public."record_media" (id_record);
CREATE UNIQUE INDEX ON public."record_statistic" (id_record);
CREATE UNIQUE INDEX ON public."personal_best_global" (id_user,id_level);
CREATE UNIQUE INDEX ON public."world_record_global" (id_level);
CREATE UNIQUE INDEX ON public."track_tournament_result" (id_tournament,id_user);
CREATE UNIQUE INDEX ON public."workshop_item" (workshop_id);
CREATE UNIQUE INDEX ON public."level_request" (workshop_id);

CREATE UNIQUE INDEX ON public.level_points(id_level);
CREATE TABLE public.user_point_contribution(id_user integer NOT NULL,id_level integer NOT NULL,id_record integer NOT NULL,contribution_rank integer NOT NULL,level_position integer NOT NULL,level_points integer NOT NULL,level_decayed_points real NOT NULL,player_decayed_points real NOT NULL,date_calculated timestamptz NOT NULL,PRIMARY KEY(id_user,id_level));
