-- Disposable test schema only. Never apply to production.
CREATE SCHEMA zc_private;
CREATE TABLE public."user" (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 steam_id bigint UNIQUE NOT NULL, steam_name text, discord_id bigint NOT NULL DEFAULT -1,
 banned boolean NOT NULL DEFAULT false, date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz
);
CREATE TABLE public.level (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 hash text NOT NULL, xx_hash text UNIQUE NOT NULL, adventure boolean NOT NULL DEFAULT false,
 has_records boolean NOT NULL DEFAULT false, record_count bigint NOT NULL DEFAULT 0,
 publicly_visible boolean NOT NULL DEFAULT true, date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz
);
CREATE TABLE public.zsl_points_structure (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL,
 points integer[] NOT NULL, minimum_points integer NOT NULL, best_of integer NOT NULL
);
CREATE TABLE public.zsl_season (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_points_structure integer NOT NULL REFERENCES public.zsl_points_structure,
 name text NOT NULL, start_date timestamptz NOT NULL DEFAULT now(), end_date timestamptz NOT NULL DEFAULT now(),
 date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz
);
CREATE TABLE public.zsl_round (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_season integer NOT NULL REFERENCES public.zsl_season,
 name text NOT NULL, round integer NOT NULL, workshop_id bigint NOT NULL DEFAULT 1,
 event_date timestamptz NOT NULL, event2_date timestamptz,
 date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz,
 UNIQUE(id_season,round)
);
CREATE TABLE public.zsl_level (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_round integer NOT NULL REFERENCES public.zsl_round, id_level integer NOT NULL REFERENCES public.level,
 date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz
);
CREATE TABLE public.zsl_level_result (
 id_level integer NOT NULL REFERENCES public.zsl_level, id_user integer NOT NULL REFERENCES public."user",
 id_record integer, position integer NOT NULL, points integer NOT NULL, time real NOT NULL,
 date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz, PRIMARY KEY(id_level,id_user)
);
CREATE TABLE public.zsl_round_result (
 id_round integer NOT NULL REFERENCES public.zsl_round, id_user integer NOT NULL REFERENCES public."user",
 position integer NOT NULL, points integer NOT NULL,
 date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz, PRIMARY KEY(id_round,id_user)
);
CREATE TABLE public.zsl_season_result (
 id_season integer NOT NULL REFERENCES public.zsl_season, id_user integer NOT NULL REFERENCES public."user",
 position integer NOT NULL, points integer NOT NULL,
 date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz, PRIMARY KEY(id_season,id_user)
);
CREATE TABLE zc_private.managed_lobby (
 key text PRIMARY KEY, join_id text NOT NULL, date_created timestamptz NOT NULL DEFAULT now(), date_updated timestamptz
);
CREATE TABLE zc_private.zsl_practice_playlist (
 id_zsl_round integer NOT NULL REFERENCES public.zsl_round,
 playlist_url text NOT NULL, object_key text NOT NULL, content_sha256 text NOT NULL, byte_size integer NOT NULL,
 date_updated timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id_zsl_round,playlist_url)
);
