import { expect, test } from 'bun:test'
import { BitReader, BitWriter } from './binary'
import {
	changeLobbyLevelsPacket,
	changeLobbyPlaylistPacket,
	parseGameHostPacket,
} from './gameServerPackets'

const first = {
	uid: 'alpha',
	workshopId: 123n,
	name: 'Café',
	collaborators: 'Zoë',
	overrideAuthorName: '',
	author: 'Åsa',
}
const second = {
	uid: 'beta',
	workshopId: 9007199254740993n,
	name: '雪道',
	collaborators: '',
	overrideAuthorName: '名',
	author: 'René',
}
const levels = [first, second]
// Independently packed LSB-first from V18 ChangeLobbyPlaylistPacket.Serialize:
// header, both OnlineZeeplevel records, then ONE bool/int32 trailer (708 bits).
// Not generated by changeLobbyLevelsPacket or BitWriter.
const GOLDEN =
	'b2eb0000000000c072400000000002000000040000000ac2d8e0d0c2f6000000000000000a86c2cc865309b4de86570108860be7c2108895d185050000000000800018a46faaa6074e020c944336164895b90da72a00000000'

function assertV18Packet(bytes: Uint8Array) {
	const reader = new BitReader(bytes)
	expect(reader.readUInt16()).toBe(60338)
	expect(reader.readFloat64()).toBe(300)
	expect(reader.readBoolean()).toBe(false)
	expect(reader.readInt32()).toBe(0)
	expect(reader.readInt32()).toBe(1)
	expect(reader.readInt32()).toBe(2)
	for (const level of levels) {
		expect(reader.readString()).toBe(level.uid)
		expect(reader.readUInt64()).toBe(level.workshopId)
		for (const value of [
			level.name,
			level.collaborators,
			level.overrideAuthorName,
			level.author,
		])
			expect(reader.readString()).toBe(value)
		expect(reader.readBoolean()).toBe(false)
	}
	expect(reader.readBoolean()).toBe(true)
	expect(reader.readInt32()).toBe(2)
	expect(reader.remainingBits).toBe(4)
	while (reader.remainingBits) expect(reader.readBoolean()).toBe(false)
}

test('matches independent V18 multi-level golden including Unicode and uint64 IDs', () => {
	const bytes = changeLobbyLevelsPacket(levels, 300, 0, 1)
	expect(Buffer.from(bytes).toString('hex')).toBe(GOLDEN)
	assertV18Packet(bytes)
	expect(parseGameHostPacket(Buffer.from(GOLDEN, 'hex'), 0n, 0)).toEqual({
		type: 'playlist',
		roundTime: 300,
		isRandom: false,
		currentIndex: 0,
		nextIndex: 1,
		levels: levels.map((level) => ({ ...level, played: false })),
		wasSynced: true,
		originalPlaylistLength: 2,
	})
})

test('strict V18 decoding rejects old per-entry trailers and trailing bytes', () => {
	const writer = new BitWriter()
	writer.writeUInt16(60338)
	writer.writeFloat64(300)
	writer.writeBoolean(false)
	writer.writeInt32(0)
	writer.writeInt32(1)
	writer.writeInt32(2)
	for (const level of levels) {
		writer.writeString(level.uid)
		writer.writeUInt64(level.workshopId)
		for (const value of [
			level.name,
			level.collaborators,
			level.overrideAuthorName,
			level.author,
		])
			writer.writeString(value)
		writer.writeBoolean(false)
		writer.writeBoolean(true)
		writer.writeInt32(1)
	}
	expect(() => assertV18Packet(writer.toUint8Array())).toThrow()
	expect(() =>
		assertV18Packet(Buffer.concat([Buffer.from(GOLDEN, 'hex'), Buffer.from([0])])),
	).toThrow()
})

test('single-track compatibility and bounded sequential indices', () => {
	expect(changeLobbyLevelsPacket([first], 300, 0, 0)).toEqual(
		changeLobbyPlaylistPacket(first, 300),
	)
	for (const [current, next] of [
		[-1, 0],
		[0, 2],
		[0.5, 0],
	] as const)
		expect(() => changeLobbyLevelsPacket(levels, 300, current, next)).toThrow()
	expect(() => changeLobbyLevelsPacket([], 300, 0, 0)).toThrow()
})
